[[questions]]
type = "MultipleChoice"
prompt.prompt = """
How much wood would a woodchuck chuck, if a woodchuck could chuck wood?
"""
answer.answer = "not enough information is available to answer this question, because no data about wood chucks chucking wood exists."
prompt.distractors = [
"one chord",
"a whole tree",
"none"
]
context = """
A wood chuck is an alternate name for a ground hog, a medium-sized rodent in the marmot family.
"""
id = "18ea4c61-c7c3-433f-add5-d3d3156e3e71"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
What elements are in water?
"""
prompt.distractors = [
"hydrogen",
"oxygen"
]
answer.answer = "both"
context = """
H2O
"""
id = "18ea4c61-c7c3-433f-add5-d3d3156e3e71"
[[questions]]
type = "ShortAnswer"
prompt.prompt = "What is the slope of the line defined by y = 3x + 7?"
answer.answer = "3"
context = """ """
id = "dbbaea6a-f469-464f-9d60-99ae98456b6a6"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
True or False: Squares are Rectangles.
"""
prompt.distractors = [
  "false"
]
answer.answer = "true"
context = """
Rectangles are 4-sided polygons with 4 right angles. Squares are the subset of rectangles that also have sides of equal length.
"""
id = "18ea4c61-c7c3-433f-add5-d3d3156e3e742"

[[questions]]
type = "Tracing"
prompt.program = """
fn main() {
  let x = 1;
  println!("{x}");
  x += 1;
  println!("{x}");
}
"""
answer.doesCompile = false
answer.lineNumber = 4
context = """
DO NOT USE THIS QUESTION TYPE - it has built in text about compilers.
"""
id = "bba6a299-b20f-4685-934a-792a591df3c0"